//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string Title { get; set; }
        public string TitleColor { get; set; }
        public string Author { get; set; }
        public string Source { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string NewsImg { get; set; }
        public Nullable<bool> IsLink { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public string Content { get; set; }
    
        public virtual NewsClass NewsClass { get; set; }
    }
}
