//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int PhotoID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string PhotoName { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string PhotoImg { get; set; }
        public string Pictures { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public byte[] Content { get; set; }
    }
}
