//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Property Property { get; set; }
    }
}
