//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_shop_product
    {
        public int ShoppingID { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<bool> IsGive { get; set; }
        public string ClassName { get; set; }
        public string PropertyName { get; set; }
        public string AttributeValue { get; set; }
        public string BrandName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public string BarCode { get; set; }
        public string Spec { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
    }
}
