//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_shopping
    {
        public string SupplierName { get; set; }
        public string StorageName { get; set; }
        public int ShoppingID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StorageId { get; set; }
        public string ShoppingCode { get; set; }
        public string ShoppingType { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<int> PayType { get; set; }
        public string UserName { get; set; }
        public string Contact { get; set; }
        public string TEL { get; set; }
        public string Address { get; set; }
    }
}
