//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StorageLocation_List
    {
        public string UserName { get; set; }
        public string RegionName { get; set; }
        public string StorageName { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string LocationCode { get; set; }
        public string LocationNum { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> MaxVol { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> AdminId { get; set; }
        public int StorageId { get; set; }
    }
}
