//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Storage_List
    {
        public string TypeName { get; set; }
        public string UserName { get; set; }
        public int StorageId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string StorageName { get; set; }
        public string StorageCode { get; set; }
        public Nullable<bool> State { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
    }
}
